#!/bin/sh

play() {
  PLAYLIST="http://a.files.bbci.co.uk/media/live/manifesto/audio/simulcast/hls/uk/sbr_high/ak/bbc_$1.m3u8"
  echo "$PLAYLIST"
  mplayer "$PLAYLIST"
}

usage() {
  echo 'Usage: radio <1-6>'
}

if [ -z "$1" ]; then
  usage
  exit
else
  xtitle Radio $1
  case "$1" in
    1) play radio_one ;;
    2) play radio_two ;;
    3) play radio_three ;;
    4) play radio_fourfm ;;
    5) play radio_five_live ;;
    6) play 6music ;;
    *) usage ;;
  esac
  xtitle Radio OFF
fi
