#!/usr/bin/env ruby

require 'docopt'
require_relative '../station'

docs = <<~EOF 
  Usage: radio <station> [ --last ]

  -l, --last    Show songs played in the last hour.
EOF

begin
  opts = Docopt::docopt(docs)
rescue Docopt::Exit => e
  puts e.message
  exit 1
end

station = Station.new(opts['<station>'])

if opts['--last']
  puts "Fetching last played songs for radio #{station.channel}"
  puts
  puts station.last_played
elsif station.found?
  system("xtitle Radio #{station.channel}")
  puts "\e[H\e[2J" # clear terminal
  begin
    station.play false do |line|
      puts line
    end
  rescue Interrupt
    puts
    puts 'Bye'
  end
else
  puts 'Error: station should be 1-6.'
  puts
  puts docs
  exit 1
end
